package com.eunidev.edcopid_19

enum class IndonesiaProvince(s: String) {
    DKI_JAKARTA("DKI Jakarta"),
    JAWA_BARAT("Jawa Barat"),
    JAWA_TIMUR("Jawa Timur"),
    JAWA_TENGAH("Jawa Tengah"),
    SULAWESI_SELATAN("Sulawesi Selatan"),
    SULAWESI_UTARA("Sulawesi Utara"),
    KALIMANTAN_TIMUR("Kalimantan Timur"),
    KALIMANTAN_TENGAH("Kalimantan Tengah"),
    RIAU("Riau"),
    SUMATERA_BARAT("Sumatera Barat"),
    BANTEN("Banten"),
    BALI("Bali"),
    SUMATERA_SELATAN("Sumatera Selatan"),
    SUMATERA_UTARA("Sumatera Utara"),
    KALIMANTAN_SELATAN("Kalimantan Selatan"),
    DAERAH_ISTIMEWA_YOGYAKARTA("Daerah Istimewa Yogyakarta"),
    PAPUA("Papua"),
    ACEH("Aceh"),
    SULAWESI_TENGGARA("Sulawesi Tenggara"),
    LAMPUNG("Lampung"),
    KEPULAUAN_RIAU("Kepulauan Riau"),
    PAPUA_BARAT("Papua Barat"),
    NTB("Nusa Tenggara Barat"),
    MALUKU("Maluku"),
    KALIMANTAN_UTARA("Kalimantan Utara"),
    SULAWESI_TENGAH("Sulawesi Tengah"),
    BENGKULU("Bengkulu"),
    GORONTALO("Gorontalo"),
    JAMBI("Jambi"),
    KALIMANTAN_BARAT("Kalimantan Barat"),
    BANGKA_BELITUNG("Bangka Belitung"),
    MALUKU_UTARA("Maluku Utara"),
    NTT("Nusa Tenggara Timur"),
    SULAWESI_BARAT("Sulawesi Barat")

}